language: node_js
node_js:
  - "0.10"
script:
  - echo 'Hello Firebase'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --email ${yutianriyue@gmail.com} --password ${g1543020544g}
